### ISSUE TITLE
Document "clean" deployment and installation flow and prepare missing steps

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-klaviyo#19]
Currently there are few missing steps to ensure app installation is smooth. 
Let's use klaviyo to document entire flow and refine what else has to be done (in CLI and template)

**Comment by lkostrowski** [comment]
Related
https://github.com/saleor/saleor-app-template/issues/80

**Comment by 2can** [comment]
Deployment tested. Both Vercel & tunnel work

![Image](https://user-images.githubusercontent.com/779644/195379928-597ae50a-df28-42d4-8063-afe80ca917bb.png)
![Image](https://user-images.githubusercontent.com/779644/195379929-817a0da6-c76c-4b0d-a021-74f791fb5cad.png)
