### ISSUE TITLE
Ensure Klaviyo is production ready

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-klaviyo#21]
This repo is a fork of app-template. It doesn't provide documentatio how to deploy it. It should:
- work smooth with CLI (app deploy)
- be documented (env variables, config)

**Comment by lkostrowski** [comment]
TODO - connect app-sdk new releases and remove duplicated code

**Comment by lkostrowski** [comment]
Add proper readme to klaviyo

**Comment by 2can** [comment]
`PUBLIC_TOKEN` input seems bit confusing, it's not clear what should be put there. If that should be `Public API Key / Site ID` maybe the placeholder should be changed to that.

![Image](https://user-images.githubusercontent.com/779644/195313715-fcd34f70-45d4-4dc0-b309-f96e03638310.png)

**Comment by 2can** [comment]
Issue for placeholder https://github.com/saleor/saleor-app-klaviyo/issues/26.
No other remarks. Closing
